


import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;


/**
 *
 * @author ADN
 */
public class ExperimentoPanel extends javax.swing.JPanel {

    private ArrayList<String> listaSequencias;
    private ArrayList<Integer> listaPacientesPat;
    private ArrayList<String> listaSequenciasG;
    private DefaultListModel estModelPac;
    private DefaultListModel potModelPac;
    private DefaultListModel estModelPacSelec;
    private boolean          selecDir;
    /**
     * Creates new form resultadoInt
     */
    public ExperimentoPanel() {
        initComponents();
        
        listaSequencias  = new ArrayList();
        listaSequenciasG = new ArrayList();
        listaPacientesPat = new ArrayList();
        estModelPac      = new DefaultListModel();
        potModelPac      = new DefaultListModel();
        estModelPacSelec = new DefaultListModel();
        
        estPacList.setModel(estModelPac);
        potListaPacientes.setModel(potModelPac);
        patronList.setModel(potModelPac);
        estPacSelectList.setModel(estModelPacSelec);
        // Botones inicializados
        estRealizarExp.setEnabled(false);
        estGuardarResultado.setEnabled(false);
        
        selecDir = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        estSpliPaneVert = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        estPatBox = new javax.swing.JComboBox();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        estLongitud = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        estMinimAp = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        estError = new javax.swing.JTextField();
        estRadioButton = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        estSexoBox = new javax.swing.JComboBox();
        jLabel59 = new javax.swing.JLabel();
        estEdadMin = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        estEdadMax = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        estPacSelectList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        estPacList = new javax.swing.JList();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        estButtonCriterios = new javax.swing.JButton();
        estRealizarExp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        estGuardarResultado = new javax.swing.JButton();
        estSplitPaneHor = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        estAreaEntrada = new javax.swing.JTextArea();
        jLabel68 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        estResTextPane = new javax.swing.JTextPane();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel77 = new javax.swing.JLabel();
        genPatBox = new javax.swing.JComboBox();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        genLongitud = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        genMinimAp = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        genError = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        genRadioButton = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        genSplitPane = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        genAreaRistras = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        genResTextPane = new javax.swing.JTextPane();
        genRealizarExp = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        potListaPacientes = new javax.swing.JList();
        potBusca = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        potError = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        potResTextPane = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        patronList = new javax.swing.JList();
        potBusca1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        patronError = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        patronResTextPane = new javax.swing.JTextPane();
        jLabel26 = new javax.swing.JLabel();
        patronSecuencia = new javax.swing.JTextField();

        jScrollPane3.setViewportView(jTextPane1);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("EXPERIMENTO ESTANDAR CON SELECCION DE PACIENTES");

        estSpliPaneVert.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel19.setBackground(new java.awt.Color(204, 204, 255));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setText("SELECCION DE PATOLOGIA");
        jLabel62.setToolTipText("");

        estPatBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estPatBoxMouseClicked(evt);
            }
        });
        estPatBox.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                estPatBoxComponentHidden(evt);
            }
        });
        estPatBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estPatBoxItemStateChanged(evt);
            }
        });
        estPatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estPatBoxActionPerformed(evt);
            }
        });
        estPatBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                estPatBoxFocusGained(evt);
            }
        });

        jLabel63.setText("Patologia:");

        jLabel64.setText("Longitud:");

        estLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estLongitudKeyTyped(evt);
            }
        });

        jLabel65.setText("Apariciones minimas:");

        estMinimAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estMinimApActionPerformed(evt);
            }
        });
        estMinimAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estMinimApKeyTyped(evt);
            }
        });

        jLabel66.setText("Error (%):");

        estError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estErrorActionPerformed(evt);
            }
        });
        estError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estErrorKeyTyped(evt);
            }
        });

        estRadioButton.setBackground(new java.awt.Color(204, 204, 255));
        estRadioButton.setText("en %");
        estRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estRadioButtonActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("CRITERIOS DE SELECCION");

        jLabel49.setText("Sexo:");

        estSexoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambos sexos", "Hombre", "Mujer" }));

        jLabel59.setText("Edad minima:");

        estEdadMin.setColumns(3);
        estEdadMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estEdadMinKeyTyped(evt);
            }
        });

        jLabel61.setText("Edad maxima:");

        estEdadMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estEdadMaxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel61)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(estEdadMax))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel49)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(estSexoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel59)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(estEdadMin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estMinimAp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estRadioButton))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel63)
                        .addGap(18, 18, 18)
                        .addComponent(estPatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel62)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estPatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel63))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel64)
                            .addComponent(estLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel66)
                            .addComponent(estError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel65)
                            .addComponent(estMinimAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estRadioButton)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(estSexoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel59)
                            .addComponent(estEdadMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61)
                            .addComponent(estEdadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane2.setViewportView(estPacSelectList);

        jScrollPane1.setViewportView(estPacList);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("SELECCION DE PACIENTES");

        jButton1.setText("Añadir paciente >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Sacar paciente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Al azar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel29)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton15.setText("Usar seleccion directa");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        estButtonCriterios.setText("Usar criterios");
        estButtonCriterios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estButtonCriteriosActionPerformed(evt);
            }
        });

        estRealizarExp.setText("Realizar experimento");
        estRealizarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estRealizarExpActionPerformed(evt);
            }
        });

        estGuardarResultado.setText("Guardar Resultado");
        estGuardarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estGuardarResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(estButtonCriterios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estRealizarExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(estGuardarResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estButtonCriterios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estRealizarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estGuardarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        estSpliPaneVert.setLeftComponent(jPanel4);

        estAreaEntrada.setBackground(new java.awt.Color(204, 204, 255));
        estAreaEntrada.setColumns(20);
        estAreaEntrada.setEditable(false);
        estAreaEntrada.setRows(5);
        estAreaEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane23.setViewportView(estAreaEntrada);

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel68.setText("Ristras de entrada:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel68)
                        .addGap(0, 363, Short.MAX_VALUE))
                    .addComponent(jScrollPane23))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel68)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        estSplitPaneHor.setLeftComponent(jPanel6);

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel67.setText("Resultado:");

        estResTextPane.setBackground(new java.awt.Color(204, 204, 255));
        estResTextPane.setEditable(false);
        jScrollPane4.setViewportView(estResTextPane);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel67)
                        .addGap(0, 608, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        estSplitPaneHor.setRightComponent(jPanel7);

        estSpliPaneVert.setRightComponent(estSplitPaneHor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel30)
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(estSpliPaneVert, javax.swing.GroupLayout.DEFAULT_SIZE, 1191, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(524, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(35, Short.MAX_VALUE)
                    .addComponent(estSpliPaneVert, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estandar", jPanel18);

        jPanel40.setBackground(new java.awt.Color(204, 204, 255));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel77.setText("SELECCION DE PATOLOGIA");

        genPatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genPatBoxActionPerformed(evt);
            }
        });

        jLabel78.setText("Patologia:");

        jLabel79.setText("Longitud:");

        genLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                genLongitudKeyTyped(evt);
            }
        });

        jLabel80.setText("Minimo de apariciones:");

        genMinimAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                genMinimApKeyTyped(evt);
            }
        });

        jLabel81.setText("Error (%):");

        genError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                genErrorKeyTyped(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setText("SELECCION DE CRITERIOS");

        genRadioButton.setBackground(new java.awt.Color(204, 204, 255));
        genRadioButton.setText("en %");
        genRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel84)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel79)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genLongitud)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel81)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genError, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel80)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genMinimAp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(genRadioButton)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel77))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel78)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genPatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genPatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78)))
                    .addGroup(jPanel40Layout.createSequentialGroup()
                        .addComponent(jLabel84)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79)
                            .addComponent(genLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel81)
                            .addComponent(genError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel80)
                            .addComponent(genRadioButton)
                            .addComponent(genMinimAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("EXPERIMENTO DE BUSQUEDA DE RISTRA GENERALIZADA");

        jLabel83.setText("Ristras de entrada:");

        genAreaRistras.setBackground(new java.awt.Color(204, 204, 255));
        genAreaRistras.setColumns(20);
        genAreaRistras.setEditable(false);
        genAreaRistras.setRows(5);
        jScrollPane26.setViewportView(genAreaRistras);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel83)
                        .addGap(0, 395, Short.MAX_VALUE))
                    .addComponent(jScrollPane26))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel83)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        genSplitPane.setLeftComponent(jPanel5);

        jLabel82.setText("Resultado:");

        genResTextPane.setBackground(new java.awt.Color(204, 204, 255));
        genResTextPane.setEditable(false);
        jScrollPane6.setViewportView(genResTextPane);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel82)
                        .addGap(0, 624, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel82)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        genSplitPane.setRightComponent(jPanel8);

        genRealizarExp.setText("Realizar experimento");
        genRealizarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genRealizarExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel39Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(genSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel39Layout.createSequentialGroup()
                        .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel39Layout.createSequentialGroup()
                                .addGap(406, 406, 406)
                                .addComponent(jLabel31))
                            .addGroup(jPanel39Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(genRealizarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(203, 203, 203)
                                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel39Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(genRealizarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genSplitPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Busqueda de ristra generalizada", jPanel38);

        jLabel22.setText("Lista de pacientes:");

        potListaPacientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        potListaPacientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(potListaPacientes);

        potBusca.setText("Buscar potenciales");
        potBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potBuscaActionPerformed(evt);
            }
        });

        jLabel23.setText("Error (%):");

        potError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                potErrorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(potBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(potError))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(potBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("Resultado:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("EXPERIMENTO DE BUSQUEDA DE PATOLOGIAS POTENCIALES");

        potResTextPane.setBackground(new java.awt.Color(204, 204, 255));
        potResTextPane.setEditable(false);
        jScrollPane7.setViewportView(potResTextPane);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(250, 250, 250)
                        .addComponent(jLabel32)
                        .addGap(0, 324, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Calculo de potenciales", jPanel37);

        jLabel24.setText("Lista de pacientes:");

        patronList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        patronList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane8.setViewportView(patronList);

        potBusca1.setText("Analisis de Patron");
        potBusca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potBusca1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Error (%):");

        patronError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patronErrorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addComponent(potBusca1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(patronError))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patronError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(potBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("Resultado:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("ANALISIS DE PATRON");

        patronResTextPane.setBackground(new java.awt.Color(204, 204, 255));
        patronResTextPane.setEditable(false);
        jScrollPane9.setViewportView(patronResTextPane);

        jLabel26.setText("Secuencia:");

        patronSecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patronSecuenciaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patronSecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel33))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(patronSecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Analisis de patron", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1262, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void estEdadMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estEdadMinKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_estEdadMinKeyTyped

    private void estEdadMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estEdadMaxKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_estEdadMaxKeyTyped

    private void estLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estLongitudKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_estLongitudKeyTyped

    private void estMinimApKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estMinimApKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_estMinimApKeyTyped

    private void estErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estErrorKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && ((caracter != ',') && (caracter != '.'))) {
            evt.consume();
        }
    }//GEN-LAST:event_estErrorKeyTyped

    private void estRealizarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estRealizarExpActionPerformed
        
        // EXPERIMENTO ESTANDARD
        int q, m, eI, eF;
        double e;
        char sexo;
        String patologia;
        
        if (estError.getText().equals("") || estLongitud.getText().equals("") || estMinimAp.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ATENCION: los campos 'Longitud', 'Error' y 'Apariciones Minimas' deben estar llenos.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if( estLongitud.getText().length() > 4 || estError.getText().length() > 3 || estMinimAp.getText().length() > 3 ){
            JOptionPane.showMessageDialog(null, "ATENCION: los campos 'Longitud', 'Error' o 'Apariciones Minimas' contienen valores fuera de rango.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if( Integer.parseInt(estError.getText()) > 100){
            JOptionPane.showMessageDialog(null, "ATENCION: el error puede ser entre 0 y 100.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (Integer.parseInt(estError.getText()) > 100 && estRadioButton.isCursorSet()){
            JOptionPane.showMessageDialog(null, "ATENCION: con el minimo de apariciones en % activado, el valor de 'Apariciones Minimas' debe ser entre 0 y 100.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            m = Integer.parseInt( estLongitud.getText());
            e = Double.parseDouble( estError.getText() )/100;
            if ( estRadioButton.isSelected()) q = (listaSequencias.size() * Integer.parseInt(estMinimAp.getText())) / 100 ;
            else q = Integer.parseInt(estMinimAp.getText());
            ArrayList<String> aux = CtrlPresAlgoritmo.getNombrePatologias();
            patologia = aux.get(estPatBox.getSelectedIndex());
            
            if( selecDir ){
                
                sexo = 'x';
                eI = 0;
                eF = 120;
            } else {
                char[] sexoA = {'x', 'm', 'f'};
                eI      = Integer.parseInt(estEdadMin.getText());
                eF      = Integer.parseInt(estEdadMax.getText());
                sexo   = sexoA[estSexoBox.getSelectedIndex()];
            }
            
            CtrlPresAlgoritmo.experimentoEstandard( listaSequencias, m, e, q, eI, eF, sexo, patologia );
            // Habilita el boto de guardar i inhabilita el de realitzar experiment
            estGuardarResultado.setEnabled(true);
            estRealizarExp.setEnabled(false);
        }
    }//GEN-LAST:event_estRealizarExpActionPerformed
    
    
    private void estButtonCriteriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estButtonCriteriosActionPerformed
        // Comprovacions
        if (estEdadMin.getText().equals("") || estEdadMax.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ATENCION: faltan campos por rellenar.\nEs necesario rellenar todos los campos.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (( estEdadMin.getText().length() > 3) || ( estEdadMax.getText().length() > 3 )) {
            JOptionPane.showMessageDialog(null, "ATENCION: la edad debe ser inferior a 1000.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if ( Integer.parseInt(estEdadMin.getText()) > Integer.parseInt(estEdadMax.getText())) {
            JOptionPane.showMessageDialog(null, "ATENCION: se ha introducido una edad minima superior a la edad maxima.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (estPatBox.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "ATENCION: aun no se han introducido patologias en el sistema.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            char[] sexo = {'x', 'm', 'f'};
            ArrayList<String> aux = CtrlPresAlgoritmo.getNombrePatologias();
            listaSequencias = CtrlPaciente.seleccionaPac(sexo[estSexoBox.getSelectedIndex()], Integer.parseInt(estEdadMin.getText()), Integer.parseInt(estEdadMax.getText()), aux.get(estPatBox.getSelectedIndex()));
            if( listaSequencias.size() > 0){
                String text = "";
                for (int i = 0; i <listaSequencias.size(); i++) text += i+1 + ". " + listaSequencias.get(i) + "\n";
                text += "\nPresione sobre 'Realizar Experimento' para llevar a cabo el mismo.";
                estAreaEntrada.setText(text);
                estRealizarExp.setEnabled(true);
                selecDir = false;
            } else {
                JOptionPane.showMessageDialog(null, "ATENCION: los pacientes seleccionados no tienen ristras de ADN.", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_estButtonCriteriosActionPerformed

    private void genPatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genPatBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genPatBoxActionPerformed

    private void genLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genLongitudKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_genLongitudKeyTyped

    private void genMinimApKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genMinimApKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_genMinimApKeyTyped

    private void genErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genErrorKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && ((caracter != ',') && (caracter != '.'))) {
            evt.consume();
        }
    }//GEN-LAST:event_genErrorKeyTyped

    private void genRealizarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genRealizarExpActionPerformed
        // EXPERIMENTO GENERALIZADA
        if (genPatBox.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "ATENCION: aun no se han introducido patologias en el sistema.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if(genLongitud.getText().equals("") || genError.getText().equals("") || genMinimAp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "ATENCION: los campos 'Longitud', 'Error' y 'Apariciones Minimas' deben estar llenos.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if( genLongitud.getText().length() > 3 || genError.getText().length() > 3 || genMinimAp.getText().length() > 3) {
            JOptionPane.showMessageDialog(null, "ATENCION: los campos 'Longitud', 'Error' o 'Apariciones Minimas' contienen valores fuera de rango.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (Integer.parseInt(genError.getText()) > 100 && genRadioButton.isCursorSet()){
            JOptionPane.showMessageDialog(null, "ATENCION: con el minimo de apariciones en % activado, el valor de 'Apariciones Minimas' debe ser entre 0 y 100.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else{
            int m, q;
            double e;
            
            ArrayList<String> aux = CtrlPresAlgoritmo.getNombrePatologias();
            listaSequenciasG = CtrlPaciente.seleccionaPac('x', 0, 200, aux.get(genPatBox.getSelectedIndex()));
            String text = "";
            if( listaSequenciasG.size() > 0){
                for(int i = 0; i < listaSequenciasG.size(); i++) text += i+1 + ". " + listaSequenciasG.get(i) + "\n";
                genAreaRistras.setText(text);

                m = Integer.parseInt( genLongitud.getText());
                e = Double.parseDouble( genError.getText() )/100;
                if ( genRadioButton.isSelected()) q =  (listaSequenciasG.size() * Integer.parseInt(genMinimAp.getText())) / 100 ;
                else q = Integer.parseInt(genMinimAp.getText());

                CtrlPresAlgoritmo.experimentoGeneralizada( listaSequenciasG, m, e, q, aux.get(genPatBox.getSelectedIndex()) );
            } else {
                genAreaRistras.setText(" No existen pacientes con la patologia " + aux.get(genPatBox.getSelectedIndex()) + " con ADN registrado.");
            }
        }
        
    }//GEN-LAST:event_genRealizarExpActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String text = "";
        boolean exp = false;
        listaSequencias.clear();
        for (int i = 0; i < estModelPacSelec.getSize(); i++){
            int nH = Integer.parseInt(estModelPacSelec.getElementAt(i).toString());
            String tmp = CtrlPresAlgoritmo.getAdnPaciente(nH);
            if (tmp.equals("") )text += i+1 + ". " + "Paciente " + nH + " no tiene ristra de ADN" + "\n";
            else{
                text += tmp + "\n";
                listaSequencias.add(tmp);
                exp = true;
            }
        }
        if( exp ) text += "\nPresione sobre 'Realizar Experimento' para llevar a cabo el mismo.";
        else text += "ATENCION:\nPara seleccion directa:\n  · Seleccione la patologia.\n  · Añada los pacientes que desee.\n\nSi ningun paciente dispone de ADN, no se realizara el experimento.";
        estAreaEntrada.setText(text);
        if( exp ){
            estRealizarExp.setEnabled(true);
            selecDir = true;
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (false == estPacList.isSelectionEmpty() &&  noContiene(estModelPacSelec, estPacList.getSelectedValue())) {
            estModelPacSelec.addElement(estPacList.getSelectedValue());
            estPacSelectList.setModel(estModelPacSelec);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (false == estPacSelectList.isSelectionEmpty()){
            estModelPacSelec.remove(estPacSelectList.getSelectedIndex());
            estPacSelectList.setModel(estModelPacSelec);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(CtrlPresAlgoritmo.getCantidadPacientes() > 0){
            Random rand = new Random();
            int x = rand.nextInt(listaPacientesPat.size() + 1);
            estModelPacSelec.clear();
            ArrayList<Integer> list = new ArrayList();
            list.addAll(listaPacientesPat);
            for( int i = 0; i < x; i++ ){
                int random = rand.nextInt(list.size());
                estModelPacSelec.addElement(list.get(random));
                list.remove(random);
            }
            estPacSelectList.setModel(estModelPacSelec);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void estRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estRadioButtonActionPerformed

    private void estMinimApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estMinimApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estMinimApActionPerformed

    private void potBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potBuscaActionPerformed
        // EXPERIMENTO POTENCIAL
        if(potError.getText().equals("") || potError.getText().length() > 3 || Integer.parseInt(potError.getText()) > 100){
            JOptionPane.showMessageDialog(null, "ATENCION: el campo 'Error' debe rellenarse con un valor entre 0 y 100.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (CtrlPresAlgoritmo.patologiasVacio()){
            JOptionPane.showMessageDialog(null, "ATENCION: aun no se han introducido patologias al sistema.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (false == potListaPacientes.isSelectionEmpty()) {
            int nh = Integer.parseInt(potListaPacientes.getSelectedValue().toString());
            if (CtrlPresAlgoritmo.getAdnPaciente(nh).equals("")){
                JOptionPane.showMessageDialog(null, "ATENCION: el paciente no tiene adn registrado.", "Aviso", JOptionPane.ERROR_MESSAGE);
            }else {
                double e = Double.parseDouble(potError.getText())/100;
                CtrlPresAlgoritmo.experimentoPotencial( nh, e );
            }
        }
    }//GEN-LAST:event_potBuscaActionPerformed

    private void estGuardarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estGuardarResultadoActionPerformed
        // Buida tot el que hi ha, neteja camps
        estResTextPane.setText("");
        estAreaEntrada.setText("");
        // Guarda resultat
        CtrlPresAlgoritmo.guardaResultado();
        // Reedita les dimensions dels split panels
        estSplitPaneHor.setDividerLocation(600);
        estSpliPaneVert.setDividerLocation(176);
        // Inhabilita boto
        estGuardarResultado.setEnabled(false);
        // Actualitza resultats
        CtrlPresAlgoritmo.actualizaResultados();
    }//GEN-LAST:event_estGuardarResultadoActionPerformed

    private void potErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_potErrorKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9') && (caracter != ',') && (caracter != '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_potErrorKeyTyped

    private void genRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genRadioButtonActionPerformed

    private void estPatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estPatBoxActionPerformed
        if(estPatBox.getSelectedIndex() != -1 ){
            listaPacientesPat = CtrlPaciente.getPacientesPatologia(CtrlPresAlgoritmo.getNombrePatologias().get(estPatBox.getSelectedIndex()));
            estModelPac.clear();
            estModelPacSelec.clear();
            for(int i = 0; i < listaPacientesPat.size(); i++) estModelPac.addElement(listaPacientesPat.get(i));
            // Assignar
            estPacList.setModel(estModelPac);
            estPacSelectList.setModel(estModelPacSelec);
        }
    }//GEN-LAST:event_estPatBoxActionPerformed

    private void estPatBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_estPatBoxFocusGained

    }//GEN-LAST:event_estPatBoxFocusGained

    private void estPatBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estPatBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_estPatBoxItemStateChanged

    private void estPatBoxComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_estPatBoxComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_estPatBoxComponentHidden

    private void estPatBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estPatBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_estPatBoxMouseClicked

    private void estErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estErrorActionPerformed

    private void potBusca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potBusca1ActionPerformed
        // BUSQUEDA DE PATRON
        if(patronError.getText().equals("") || patronError.getText().length() > 3 || Integer.parseInt(patronError.getText()) > 100){
            JOptionPane.showMessageDialog(null, "ATENCION: el campo 'Error' debe rellenarse con un valor entre 0 y 100.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (patronSecuencia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ATENCION: aun no se ha introducido ninguna sequencia.", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (false == patronList.isSelectionEmpty()) {
            int nh = Integer.parseInt(patronList.getSelectedValue().toString());
            if (CtrlPresAlgoritmo.getAdnPaciente(nh).equals("")) JOptionPane.showMessageDialog(null, "ATENCION: el paciente no tiene adn registrado.", "Aviso", JOptionPane.ERROR_MESSAGE);
            else {
                double e = Double.parseDouble(patronError.getText())/100;
                // Llamada
                CtrlPresAlgoritmo.experimentoPatronIndependiente( nh, e, patronSecuencia.getText());
            }
        }
   }//GEN-LAST:event_potBusca1ActionPerformed

    private void patronErrorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patronErrorKeyTyped

   }//GEN-LAST:event_patronErrorKeyTyped

    private void patronSecuenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patronSecuenciaKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter != 'A') && (caracter != 'C') && (caracter != 'G') && (caracter != 'T')) {
            evt.consume();
        }
    }//GEN-LAST:event_patronSecuenciaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea estAreaEntrada;
    private javax.swing.JButton estButtonCriterios;
    private javax.swing.JTextField estEdadMax;
    private javax.swing.JTextField estEdadMin;
    private javax.swing.JTextField estError;
    private javax.swing.JButton estGuardarResultado;
    private javax.swing.JTextField estLongitud;
    private javax.swing.JTextField estMinimAp;
    private javax.swing.JList estPacList;
    private javax.swing.JList estPacSelectList;
    private javax.swing.JComboBox estPatBox;
    private javax.swing.JRadioButton estRadioButton;
    private javax.swing.JButton estRealizarExp;
    private javax.swing.JTextPane estResTextPane;
    private javax.swing.JComboBox estSexoBox;
    private javax.swing.JSplitPane estSpliPaneVert;
    private javax.swing.JSplitPane estSplitPaneHor;
    private javax.swing.JTextArea genAreaRistras;
    private javax.swing.JTextField genError;
    private javax.swing.JTextField genLongitud;
    private javax.swing.JTextField genMinimAp;
    private javax.swing.JComboBox genPatBox;
    private javax.swing.JRadioButton genRadioButton;
    private javax.swing.JButton genRealizarExp;
    private javax.swing.JTextPane genResTextPane;
    private javax.swing.JSplitPane genSplitPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField patronError;
    private javax.swing.JList patronList;
    private javax.swing.JTextPane patronResTextPane;
    private javax.swing.JTextField patronSecuencia;
    private javax.swing.JButton potBusca;
    private javax.swing.JButton potBusca1;
    private javax.swing.JTextField potError;
    private javax.swing.JList potListaPacientes;
    private javax.swing.JTextPane potResTextPane;
    // End of variables declaration//GEN-END:variables

    void actualizaPatologias() {
        ArrayList<String> aux = CtrlPresAlgoritmo.getNombrePatologias();
        estPatBox.removeAllItems();
        genPatBox.removeAllItems();
        for(int i = 0; i < aux.size(); i++){
            estPatBox.addItem(aux.get(i));
            genPatBox.addItem(aux.get(i));
        }
    }

    void actualizaPacientes() {
        ArrayList<Integer> aux = CtrlPresAlgoritmo.getNombrePacientes();
        potModelPac.clear();
        for(int i = 0; i < aux.size(); i++){
            potModelPac.addElement(aux.get(i));
        }
        potListaPacientes.setModel(potModelPac);
        patronList.setModel(potModelPac);
    }

    private boolean noContiene(DefaultListModel model, Object obj) {
        for (int i = 0; i < model.getSize(); i++) if(model.getElementAt(i).equals(obj)) return false;
        return true;
    }
    public void mostrarResultadoExperimentoEstandard( String texto ){
        
        estResTextPane.setContentType("text/html");
        
        estResTextPane.setText( texto );
        jScrollPane3.getVerticalScrollBar().setValue(jScrollPane3.getVerticalScrollBar().getMinimum());
        jScrollPane3.getVerticalScrollBar().setValueIsAdjusting(true);

    }
    public void mostrarResultadoExperimentoPotencial( String texto ){
        
        potResTextPane.setContentType("text/html");
        
        potResTextPane.setText( texto );
        jScrollPane3.getVerticalScrollBar().setValue(jScrollPane3.getVerticalScrollBar().getMinimum());
        jScrollPane3.getVerticalScrollBar().setValueIsAdjusting(true);
        
    }
    public void mostrarResultadoExperimentoPatronPersonalizado( String texto ){
        
        patronResTextPane.setContentType("text/html");
        
        patronResTextPane.setText( texto );
        jScrollPane3.getVerticalScrollBar().setValue(jScrollPane3.getVerticalScrollBar().getMinimum());
        jScrollPane3.getVerticalScrollBar().setValueIsAdjusting(true);
        
    }
    public void mostrarResultadoExperimentoGeneralizada( String texto ){
        
        genResTextPane.setContentType("text/html");
        
        genResTextPane.setText( texto );
        jScrollPane3.getVerticalScrollBar().setValue(jScrollPane3.getVerticalScrollBar().getMinimum());
        jScrollPane3.getVerticalScrollBar().setValueIsAdjusting(true);

    }
    public JSplitPane getEstSplitPaneHort() {
        return estSplitPaneHor;
    }
    public JSplitPane getEstSplitPaneVer(){
        return estSpliPaneVert;
    }
    public JSplitPane getGenSplitPane() {
        return genSplitPane;
    }
}
