

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author ADN
 */
public class MainInterficie extends javax.swing.JFrame {

    // Panells
    private PacientePanel   pacPan;
    private PatologiaPanel  patPan;
    private SintomaPanel    sinPan;
    private ResultadoPanel  resPan;
    private ExperimentoPanel expPan;
    /**
     * Creates new form MainInterficie
     */
    public MainInterficie() {
        initComponents();
        
        // Assigna jPanels
        pacPan = new PacientePanel();
        patPan = new PatologiaPanel();
        sinPan = new SintomaPanel();
        resPan = new ResultadoPanel();
        expPan = new ExperimentoPanel();
        panelPacientes.add(pacPan);
        panelPatologia.add(patPan);
        panelSintoma.add(sinPan);
        panelResultado.add(resPan);
        panelExperimento.add(expPan);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
 
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });
    }
 
    private void close(){
        int opcio = JOptionPane.showConfirmDialog(null, "¿Quieres guardar los ultimos cambios?");
        if(opcio == 0){
            guardarFicheroTodos();
            System.exit(0);
        }else if(opcio == 1){
            System.exit(0);
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        panelExperimento = new javax.swing.JPanel();
        panelPacientes = new javax.swing.JPanel();
        panelPatologia = new javax.swing.JPanel();
        panelSintoma = new javax.swing.JPanel();
        panelResultado = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFichero = new javax.swing.JMenu();
        fNuevo = new javax.swing.JMenuItem();
        fGuardar = new javax.swing.JMenu();
        gGeneral = new javax.swing.JMenuItem();
        gPacientes = new javax.swing.JMenuItem();
        gPatologias = new javax.swing.JMenuItem();
        gSintomas = new javax.swing.JMenuItem();
        gResultados = new javax.swing.JMenuItem();
        fCargar = new javax.swing.JMenuItem();
        fSalir = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        aAyuda = new javax.swing.JMenuItem();
        aCuanto = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jButton10.setText("Eliminar patologia");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelExperimento.setLayout(new javax.swing.BoxLayout(panelExperimento, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane.addTab("Experimento", panelExperimento);

        panelPacientes.setLayout(new javax.swing.BoxLayout(panelPacientes, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane.addTab("Pacientes", panelPacientes);

        panelPatologia.setLayout(new javax.swing.BoxLayout(panelPatologia, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane.addTab("Patologias", panelPatologia);

        panelSintoma.setLayout(new javax.swing.BoxLayout(panelSintoma, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane.addTab("Sintomas", panelSintoma);

        panelResultado.setLayout(new javax.swing.BoxLayout(panelResultado, javax.swing.BoxLayout.LINE_AXIS));
        jTabbedPane.addTab("Resultados", panelResultado);

        mFichero.setText("Fichero");

        fNuevo.setText("Nuevo espacio de trabajo");
        fNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNuevoActionPerformed(evt);
            }
        });
        mFichero.add(fNuevo);

        fGuardar.setText("Guardar");

        gGeneral.setText("Guardado general");
        gGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gGeneralActionPerformed(evt);
            }
        });
        fGuardar.add(gGeneral);

        gPacientes.setText("Pacientes");
        gPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPacientesActionPerformed(evt);
            }
        });
        fGuardar.add(gPacientes);

        gPatologias.setText("Patologías");
        gPatologias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gPatologiasActionPerformed(evt);
            }
        });
        fGuardar.add(gPatologias);

        gSintomas.setText("Síntomas");
        gSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSintomasActionPerformed(evt);
            }
        });
        fGuardar.add(gSintomas);

        gResultados.setText("Resultados");
        gResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gResultadosActionPerformed(evt);
            }
        });
        fGuardar.add(gResultados);

        mFichero.add(fGuardar);

        fCargar.setText("Cargar fichero");
        fCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCargarActionPerformed(evt);
            }
        });
        fCargar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fCargarKeyPressed(evt);
            }
        });
        mFichero.add(fCargar);

        fSalir.setText("Salir");
        fSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSalirActionPerformed(evt);
            }
        });
        mFichero.add(fSalir);

        jMenuBar1.add(mFichero);

        mAyuda.setText("Ayuda");

        aAyuda.setText("Ayuda");
        aAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAyudaActionPerformed(evt);
            }
        });
        mAyuda.add(aAyuda);

        aCuanto.setText("Cuanto a...");
        aCuanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCuantoActionPerformed(evt);
            }
        });
        mAyuda.add(aCuanto);

        jMenuBar1.add(mAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("tab1;tab2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gResultadosActionPerformed
        resPan.guardarFicheroRes();
    }//GEN-LAST:event_gResultadosActionPerformed

    private void gSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSintomasActionPerformed
        sinPan.guardarFicheroSin();
    }//GEN-LAST:event_gSintomasActionPerformed

    private void aCuantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCuantoActionPerformed
        JOptionPane.showMessageDialog(null, " Equipo de programacion:\n ·   Daniel Martinez Cruz\n ·   Eric Gutierrez Llopis\n ·   Ferran Olle Baiget\n ·   Merce Pedraza Gutierrez", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aCuantoActionPerformed

    private void aAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAyudaActionPerformed
        AyudaInt ayuI = new AyudaInt();
        ayuI.setLocationRelativeTo(null);
        ayuI.setVisible(true);
    }//GEN-LAST:event_aAyudaActionPerformed

    private void fSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSalirActionPerformed
        int opcio = JOptionPane.showConfirmDialog(null, "¿Quieres guardar los ultimos cambios?");
        if(opcio == 0){
            guardarFicheroTodos();
            System.exit(0);
        }else if(opcio == 1){
            System.exit(0);
        }
    }//GEN-LAST:event_fSalirActionPerformed

    private void fCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCargarActionPerformed
        // CARGAR FICHERO
        //Crea un nuevo filtro
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto","txt");
        //Es crea el filechooser
        JFileChooser buscF = new JFileChooser();
        //S'afegeix el filtre
        buscF.setFileFilter(filter);
        //Títol de finestra
        buscF.setDialogTitle("Selecciona el archivo .txt");
        int result = buscF.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) CtrlPresentation.recuperaFicheroGeneral(buscF);
        actualizaPacientes();
        actualizaPatologias();
        actualizaSintomas();
        resPan.actualizaResultados();
    }//GEN-LAST:event_fCargarActionPerformed

    private void fNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNuevoActionPerformed
        int opcio = JOptionPane.showConfirmDialog(null, "¿Quieres guardar los ultimos cambios?");
        if(opcio == 0){
            guardarFicheroTodos();
            CtrlPresentation.nuevoEntorno();
            pacPan.actualizaPacientes();
            patPan.actualizaPatologias();
            sinPan.actualizaSintomas();
            resPan.actualizaResultados();
            //Limpiar campos
            pacPan.restablecerTabPaciente();
            patPan.restablecerTabPatologia();
            sinPan.restablecerTabSintoma();
            resPan.limpiaResultados();
        }else if(opcio == 1){
            CtrlPresentation.nuevoEntorno();
            pacPan.actualizaPacientes();
            patPan.actualizaPatologias();
            sinPan.actualizaSintomas();
            resPan.actualizaResultados();
            //Limpiar campos
            pacPan.restablecerTabPaciente();
            patPan.restablecerTabPatologia();
            sinPan.restablecerTabSintoma();
            resPan.limpiaResultados();
        }
    }//GEN-LAST:event_fNuevoActionPerformed

    private void gPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gPacientesActionPerformed
        pacPan.guardarFicheroPac();
    }//GEN-LAST:event_gPacientesActionPerformed

    private void gGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gGeneralActionPerformed
        guardarFicheroTodos();
    }//GEN-LAST:event_gGeneralActionPerformed

    private void gPatologiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gPatologiasActionPerformed
        patPan.guardarFicheroPat();
    }//GEN-LAST:event_gPatologiasActionPerformed

    private void fCargarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fCargarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCargarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterficie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterficie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterficie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterficie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainInterficie().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aAyuda;
    private javax.swing.JMenuItem aCuanto;
    private javax.swing.JMenuItem fCargar;
    private javax.swing.JMenu fGuardar;
    private javax.swing.JMenuItem fNuevo;
    private javax.swing.JMenuItem fSalir;
    private javax.swing.JMenuItem gGeneral;
    private javax.swing.JMenuItem gPacientes;
    private javax.swing.JMenuItem gPatologias;
    private javax.swing.JMenuItem gResultados;
    private javax.swing.JMenuItem gSintomas;
    private javax.swing.JButton jButton10;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mFichero;
    private javax.swing.JPanel panelExperimento;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JPanel panelPatologia;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JPanel panelSintoma;
    // End of variables declaration//GEN-END:variables

    //_____________ACTUALIZACIONES_____________
    public void actualizaPatologias(){
        pacPan.actualizaPatologias();
        patPan.actualizaPatologias();
        sinPan.actualizaPatologias();
        expPan.actualizaPatologias();
    }
    
    public void actualizaSintomas(){
        pacPan.actualizaSintomas();
        patPan.actualizaSintomas();
        sinPan.actualizaSintomas();
    }
    
    public void actualizaPacientes() {
        pacPan.actualizaPacientes();
        expPan.actualizaPacientes();
    }
    
    public void actualizaResultados() {
        resPan.actualizaResultados();
    }
    
    //_____________CAMBIO DE TAB_______________    
    public void muestraTabPatologia(){
	jTabbedPane.setSelectedIndex(2);
    }

    public void muestraTabSintoma(){
            jTabbedPane.setSelectedIndex(3);
    }
    //____________GUARDAR FICHEROS_____________
    private void guardarFicheroTodos() {
        pacPan.guardarFicheroPac();
        patPan.guardarFicheroPat();
        sinPan.guardarFicheroSin();
        //guardarFicheroRes();
    }

    public ExperimentoPanel getExpPan() {
        return expPan;
    }
}
