

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;


/**
 *
 * @author Ferran
 */
public class ResultadoPanel extends javax.swing.JPanel {

    private DefaultListModel modelRes;
    
    /**
     * Creates new form ResultadPanel
     */
    public ResultadoPanel() {
        
        initComponents();
        
        modelRes = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jListaRes = new javax.swing.JList();
        jPanel24 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resPanellText = new javax.swing.JTextPane();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jScrollPane9.setViewportView(jListaRes);

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setText("Resultado:");

        resPanellText.setEditable(false);
        jScrollPane1.setViewportView(resPanellText);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addGap(0, 958, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton20.setText("Consulta");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("Eliminar resultado");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel4.setText("Lista de resultados:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private static String cabecera(){
        String c = "";
        c += "<html><head><style type=\"text/css\">" + estilo() + "</style></head>";
        return c;
    }
    
    
    private static String estilo(){
        String c = "";
        c += 
          "body{ margin: 0; padding: 0; background-color: white;/*#F7F7F7;*//*#A6CEEA;*/ font-family: \"Palatino Linotype\", Verdana, Arial; /*\"Baskerville Old Face\"*/ font-size: 10px; }" 
        + "table{ margin: 0; padding: 0; width: 100%; background-color: #F7F7F7;/*#A6CEEA;*/ font-size: 10px; }" 
        + ".tituloT{ margin: 0; padding: 2px 0 5px 0; background-color: /*#F7F7F7;*/#A6CEEA; text-align:center;font-size: 11px; }"
        + ".tituloT2{ margin: 0; padding: 2px 0 5px 0; background-color: /*#F7F7F7;*/#A6CEEA; text-align:center;font-size: 11px; }" 
        + ".thInfo{ margin: 0; padding: 0px 10px 0px 0; text-align:right;}"
        + ".thPat{ padding: 2px 0 10px 5px; height:10px; color:white; background-color: #2B547E/*#F7F7F7;*/ /*#B0E0E6*/; text-align:left;}" 
        + ".tdNormal{ padding: 2px 0 0px 0; text-align:left; font:bold 9px \"Palatino Linotype\", Verdana, Arial;  }" 
        + ".tdNormalFlojo{ height: 5px; border-spacing:0; padding: 0; text-align:left; font:bold 9px \"Palatino Linotype\", Verdana, Arial; color: #808080;  }" 
        + ".tdNormalFlojo span{ margin: 0; padding: 0;}"
        + ".tdNormalFlojo .spanCont{ color: black; margin: 0; padding: 0;}"
        + "#A{color:#DCDCDC; background-color: #0000CD; display:block;} " 
        + "#C{color:#DCDCDC; background-color: #FF0000; display:block;} " 
        + "#G{color:black; background-color: #32CD32; display:block;}"  
        + "#T{color:black; background-color: #FFD700; display:block;}";
        
        return c;
    }
    
    
    
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // Consulta el resultado
        if (false == jListaRes.isSelectionEmpty()) {
            int aux = Integer.parseInt(jListaRes.getSelectedValue().toString());
            //ArrayList<String> p = CtrlPresResultado.getResultado(aux);
            
            String t = CtrlPresResultado.mostrarResultado(aux);

            if (!t.isEmpty()) {
                resPanellText.setContentType("text/html");
                resPanellText.setText(cabecera() + t);
            }
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        if (false == jListaRes.isSelectionEmpty()) {
            int pos = jListaRes.getSelectedIndex();
            CtrlPresResultado.eliminarResultado(Integer.parseInt(jListaRes.getSelectedValue().toString()));
            modelRes.remove(pos);
        }
        CtrlPresResultado.actualizaResultado();
        limpiaResultados();
    }//GEN-LAST:event_jButton21ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JList jListaRes;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane resPanellText;
    // End of variables declaration//GEN-END:variables

    
    public void guardarFicheroRes() {
        //Es crea el filechooser
        JFileChooser direc = new JFileChooser();
        //Títol de finestra
        direc.setDialogTitle("Guardar fichero de resultados");
        //Canviar el text del boto
        direc.setApproveButtonText("Guardar");
        int result = direc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) CtrlPresResultado.guardarResultados(direc);
    }
    
     public void actualizaResultados() {
        ArrayList<Integer> listaRes = CtrlPresResultado.getIdResultados();
        modelRes = new DefaultListModel();
        for(int i = 0; i < listaRes.size(); i++) modelRes.addElement(listaRes.get(i));
        jListaRes.setModel(modelRes);
    }
     
     public void limpiaResultados(){
        resPanellText.setText("");
     }
}
